version: '3'
services:
  monorepo:
    container_name: monorepo
    build:
      context: './'
      dockerfile: Dockerfile
    ports:
      - 4200:4200
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    tty: true

  db:
    container_name: db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/

volumes:
  fdj-data: